import type { Metadata } from "next";
import "./globals.css";
import { ralewayFont } from "./fonts";

export const metadata: Metadata = {
  title: "Denis Larin",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ralewayFont.className} antialiased text-slate-300 bg-m-dark`}
      >
        {children}
      </body>
    </html>
  );
}
